# Generated by Django 4.0.3 on 2022-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_detail_name_detail_pword'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
